name: '[PSH] Quality Engineering'

on:
  push:
    branches:
      - master
      - main
      - test/new-workflow

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@next-version
    with:
      nodeLint: true
      nodeTest: true
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_b2b-organizations-graphql
      nodeSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
